services:
  database:
    image: postgres:16
    container_name: droncast_database
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: droncast_adminer
    ports:
      - 8080:8080

  backend: &app
    image: ${BACKEND_IMAGE}
    build:
      args:
        PIPENV_EXTRAS: ${PIPENV_EXTRAS}
    container_name: droncast_app
    env_file: ".env"
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./src:/app/src

volumes:
  pg-data: {}
